version: "3.3"
services:
  garden-frontend-dev:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    container_name: garden-frontend-dev
    volumes:
      - /home/mat/docker/garden-app/frontend/src:/app/src:z
      - /home/mat/docker/garden-app/frontend/public:/app/public:z
      - /home/mat/docker/garden-app/frontend/rollup.config.js:/app/rollup.config.js:z
  garden-backend-dev:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    container_name: garden-backend-dev
    volumes:
      - ./backend:/app:z